#!/bin/bash
OUT_FILE="src.pri"

DIRS="kernel drivers src boot"

function generate_header {
cat << eom
# File automatically generated by $0. Do not edit manually.
eom
}

function generate_dirs {
dirs=`find $DIRS -mindepth 1 -type d | tr "\n" " " | grep -v Demo`
echo "DEPENDPATH += . ${dirs}"
echo "INCLUDEPATH += . ${dirs}"
echo ""
}

function generate_header_files {
files=`find $DIRS -type f -iname "*.h" -o -iname "*.hpp" | sort | grep -v Demo`
echo "HEADERS += \\"
for i in $files ; do
	echo "           $i \\"
done
echo
}

function generate_src_files {
files=`find $DIRS -type f -iname "*.c" -o -iname "*.cpp" | sort | grep -v Demo`
echo "SOURCES += \\"
for i in $files ; do
	echo "           $i \\"
done
echo
}


generate_header > $OUT_FILE
generate_dirs >> $OUT_FILE
generate_header_files >> $OUT_FILE
generate_src_files >> $OUT_FILE
